from Library import Library

my_lib = Library()
print("----------")
my_lib.create_tables()
print("----------")
my_lib.add_book("harry potter","j. k. rowling", "1997")
print("----------")
my_lib.add_reader("maksim","18")
print("----------")
my_lib.borrow_book(2,4)
print("----------")
my_lib.return_book(3,6)
print("----------")
my_lib.search_books('harry potter')
print("----------")
my_lib.get_borrowed_books()
print("----------")
my_lib.get_statistics()
print("----------")